index.js

If itemWidth prop is updated, the new card positions is not calculated again. So I create this PR to update for this case.

Refresh card positions if itemWidth prop has new value

---

index.js

I was getting problems in my implementation when rotating the device, cards were resizing but not being positioned correctly.
I saw there was a TODO to handle the device orientation event but I found that binding `_calcCardPositions` to `onLayout` for the parent `ScrollView` seemed to work well for me.

Recalculate card positions on layout to handle rotation

---

index.js

* `Animated.parallel(…)` was introduced in 42e5533.
* This leads to killed animated in case of `snapToItem` calls as you can see in the captures below
* I manually `snapToItem` when the user "taps" on an item
* Before the usage of `Animated.parallel(…)` the animations for active and inactive slides were correctly running
* After the usage of `Animated.parallel(...)` the animation of the now inactive slide was aborted. This is shown in the second capture at "Item 32"
* I couldn't find any drawbacks in reverting to not-using `Animated.parallel`

Reverts „Animated.parallel“ due to animation bug

---

src/carousel/Carousel.js

Added pointerEvents="box-none" to item wrapper to prevent blocking touches when items are overlapping and have touchable children.

Preventing blocking touches on overlapping items

---

README.md

Proposal:
Add link to React Native's feature requests issue to readme so that more people see it and vote!!

Add visibility to React Native's feature requests issue

---

src/carousel/Carousel.js

All child elements with ScrollView is given key `scrollview-item-{$index}`. 
When the source data elements index positions change, due to sort / pop; the rendered item gets re-created. This patch enables keyExtractor prop to apply keys for ScrollView as well.

Support keyExtractor on ScrollView

---

src/carousel/Carousel.js

We have a use case where a carousel is the second page of a `pagingEnabled={true}` scrollview. I know that nesting is frowned upon, but we've gotten it to mostly work. We set the carousel's `scrollEnabled` to `true`, and the outer's to `false`, when the outer scrollview hits the second page. 
However, we noticed the first card required scrolling all the way to the next page before we could easily swipe between cards:
If we allow changing scrollEnabled to true in `componentWillReceiveProps`, we can accept a `scrollEnabled` change before any user interaction:
This might also address some issues referencing the scroll "bouncing back" to the first card.

Allow changing scrollEnabled to true from initially false

---

src/carousel/Carousel.js

reference:
https://github.com/facebook/react-native/issues/16920
https://github.com/facebook/react-native/issues/16542

fix(carousel): Animated.View.propTypes will cause crash in release mode

---

src/parallaximage/ParallaxImage.js

This is probably linked to issue #310 and maybe #185.
My issue was that sometimes the ParallaxImage wasn't displayed, I got stuck with the loader.
I realised that when `_measureLayout` is called as the callback of the `onLayout` prop of the `View`, `this` is not the `ParallaxImage` but the global scope.
Therefore `this._container` is not defined and the image's dynamic style props are not updated.
This seems to fix the issue permanently.

Fix ParallaxImage not being rendered

---

src/carousel/Carousel.js

All
Snap is not working correctly after `scrollEnabled` was changed repeatedly.
I guess this is because of the previous PR (#390).
-----
Step 1. Set scrollEnabled={true}
Step 2. Set scrollEnabled={false}
Step 3. Set scrollEnabled={true}
Step 4. Snap is not working correctly.
[Here](https://github.com/archriss/react-native-snap-carousel/blob/v3.7.4/src/carousel/Carousel.js#L479) is where the problem occurs. In Step 3, this._setScrollEnabled(true) is called.
```js
value = value && this.props.scrollEnabled; // value = true && false; value is false
```
I tried to make the related logic work a little more efficiently. I hope this helps.
After applying this patch, You can see if the above steps reproduce the problem I pointed out.

Fixed incorrect snap issue after scrollEnabled was changed.

---

src/carousel/Carousel.js
src/pagination/Pagination.js
src/pagination/PaginationDot.js

All
Adds optional `accessibilityLabel` to `<Pagination />` component so it's possible to e.g. display which slide we're showing when focusing is on pager.
We're using this in one of the projects I'm working on and wanted to back-port the change to upstream :)

feat: add accessibilityLabel to Pagination

---

src/carousel/Carousel.js

All
This PR is for allowing to pass a serializable Animated.event as an onScroll property, I was trying to spread the array of maps that use Animated.event as the first argument but react-native was just using the first item in that array of maps, so I made a fix for using or sharing the animated value passed as prop instead of the one that it's defined in the library.
using a regular callback as a prop for onScroll and using an Animated.event with useNativeDriver set on
I'm going to be testing the feature listed below, to be sure this change doesn't break anything.
The next gif link is some evidence that despite that this ticket was just about using Animated.event, it is not breaking custom interpolations, so in order to show you that, I'm going to [comment this block of …

feature: allow serialized animated event as onScroll

---

src/carousel/Carousel.js

iOS & Android
User can provide custom scroll component with `useScrollView` prop.
If previous layouts (layout, stack or tinder) are still working with `useScrollView` of values: `false`, `true` or custom component. 
```jsx
import { ScrollView } from 'react-native-gesture-handler'
const AnimatedScrollView = Animated.createAnimatedComponent(ScrollView);
// render
<Carousel
useScrollView={AnimatedScrollView}
renderItem={this.renderItem}
itemWidth={250}
sliderWidth={windowWidth}
data={data}
{...props}
/>
```
I choose to use the already existing prop `useScrollView` because I think it suits well the feature needed and it's pretty transparent of what this prop can do.
Previously, I wanted to use the same props as FlatList `renderScrollComponent` but I encounter conflicts between the way that …

Custom Scroll Component

---

src/carousel/Carousel.js

all
fire the onTouchStart prop in carousel
the onTouchStart prop didn't fire in the previous code, which may end in unwanted result.
an online demo here: https://snack.expo.io/@sanglewang/react-native-snap-carousel-demo
in the case, we have two nested vertical scrollview, on android only the outside scroll view can be scrolled. we add a state to control the scrollEnabled prop to hack it. since the onTouchStart prop did not fire in the carousel, the state will never turn to false, and the carousel cannot mannully scroll.
I was wondering why the other event props (onScrollEndDrag, onMomentumScrollEnd etc. ) are fired in the component and the onTouchStart is not. Is there any protential problem i ignored ?

feat: fire the onTouchStart prop

---

src/carousel/Carousel.js

iOS, Android
It allows the `contentContainerCustomStyle` prop override the default paddings. The default paddings do not always work nicely with all designs.
The change itself is pretty trivial.
Tested on Android And iOS for a simple use-case
```js
<Carousel
...
contentContainerCustomStyle={{ backgroundColor: 'red', paddingLeft: 10, paddingRight: 0 }}
/>
```

Allow contentContainerCustomStyle override default paddings.

---

src/carousel/Carousel.js
src/pagination/PaginationDot.js

iOS and android
removing componentWillReceiveProps deprecated warning
nothing really

componentWillReceiveProps migrated to componentDidUpdate

---

src/carousel/Carousel.js

Both iOS and Android
Fix autoplay stops after user interaction https://github.com/archriss/react-native-snap-carousel/issues/452.
Scroll manually if `autoplay = true`, or after calling `startAutoplay`, and it should continue autoplay after scrolling.

Fix autoplay stops after user interaction

---

src/index.d.ts

Developer experience (?)
Library is lacking TypeScript support. This PR adds basic module declaration to suppress warnings that might pop when using TypeScript. I know it can be heavily modified and improved but since I had to do It already for a private project I didn't see why I shouldn't create this PR.
Tested import for Carousel, Pagination and ParallaxImage with and without required props.

 🏷️ Add basic TS support

---

src/carousel/Carousel.js

ANDROID
On Android, when enableMomentum is true, snapToItem no longer works. You are not able to click the next carousel item to navigate through the carousel, only swiping works. It looks like this iOS fix applies to Android in the case of enableMomentum being true, and allows navigation via snapToItem. On the snack.io: https://snack.expo.io/@daaashley/snap-carousel-snaptoitem-bug-android , notice how on iOS emulator you can navigate by clicking, and on Android you cannot. If you merge/try out this change, you will be able to navigate via click/snapToItem on Android. Please let me know your thoughts, comments, advice, etc... 
I have made a snack example to demonstrate the problem and reproduced and fixed the problem locally, a fix which I have submitted here. …

snapToItem does not work on Android with momentumEnabled

---

src/carousel/Carousel.js

This is referring to issues related to firstItem rendering not working reliably. (#538, #193 )
By using `getItemLayout` & `initialScrollIndex`, I am able to pass the relevant values to `FlatList` and resolve the wrong `firstItem` being rendered without having to `useScrollView` or set `initialNumToRender={data.length}`.
make sure to understand how to use both properties together:
https://facebook.github.io/react-native/docs/flatlist#initialscrollindex
https://facebook.github.io/react-native/docs/flatlist#getitemlayout

remove override to flatlist built in functionality needed for initial item rendering bug

---

src/carousel/Carousel.js

Those extra `clearTimeout` fixes 2 potential issues with timeouts firing after programatically calling `stopAutoplay()`: 
- If a `stopAutoplay()` is issued while there is an unfulfilled delayed autoplay (because of `autoplayDelay`), the autoplay will start anyway because `_autoplayTimeout` is still up. 
- If the carousel item is clickable, and the click should stop autoplay (with `stopAutoplay()`), because of the `_onScrollEnd` fallback for Android (and the `+50` added to the `autoplayDelay` there), there was a chance that the carousel would continue scrolling automatically.

Clear all timeouts when stopping autoplay

---

src/carousel/Carousel.js

iOS, Android
Fixed snapToItem not working correctly.
Tested on iOS / Android

Fix for incorrect snapToItem

---

src/pagination/Pagination.js
src/pagination/PaginationDot.js

iOS, Android
Simply fixes [this issue.
](https://github.com/archriss/react-native-snap-carousel/issues/626)
Fixes the issue of pagination dots throwing an error and not working when clicked. Setting `tappableDots={true}` resulted in an error due to the carousel ref not being referenced correctly.
Also makes the generation of dots functional by using `map` instead of `push`.
It's only been tested on Android. Setting `carouselRef` to an incorrect type results in a warning.

Fix for issue #626 carouselRef.getPositionIndex is not a function

---

src/carousel/Carousel.js

Android, iOS
When you try to snap to the first item, using the `snapToItem` function, it doesn't work. It works for all but the first element. e.g.
```javascript
carouselRef.current?.snapToItem(0) // this doesn't works
carouselRef.current?.snapToItem(1) // this works
```
I tested the fix in my app and it works as expected, anyway, It's just a minor change.

Fix: Snapping to the first item not working

---

src/carousel/Carousel.js

Android & iOS
There is api change since RN 0.62.x, so calling `getNode` is no longer necessary. This PR just make sure get the correct ref for both 0.62.x and below.
- Carousel works well and no error with `snapToItem` call (Tested on RN 0.62.2 and 0.61.5 by @alessandro-bottamedi)

Get correct carousel ref for RN 0.62.x
